#!/bin/bash

set -eu

join_by() {
    local IFS="$1"  # Set the delimiter
    shift           # Shift to get to the elements
    echo "$*"         # Print all elements joined by the delimiter
}

accs_opposited=(
            "^Capitaux"
            # "^Immobilisations:Amortissements"
            # "^Tiers:OrganismesSociaux"
            # "Tiers:GroupeEtAssociés"
            #"RabaisRemisesRistournesObtenusSurAchats"    
            #"Charges:AutresServicesExtérieurs:RémDIntermédiairesEtHonoraires:CommsEtCourtagesSurVentes"
            "^Produits"
            )

joined_accs_opposited=$(join_by "|" "${accs_opposited[@]}")

# balance format
# modify balance format to better reflect what is happenning economically
# default %(ansify_if(justify(scrub(display_total), 20, 20 + int(prepend_width), true, color), bold if should_bold)) %(!options.flat ? depth_spacer : "") %-(ansify_if(ansify_if(partial_account(options.flat), blue if color), bold if should_bold)) \n%/%$1\n%/%(prepend_width ? " " * int(prepend_width) : "")--------------------\n
balance_format='%(ansify_if(justify(scrub(display_total * (account =~ /'
balance_format+=$joined_accs_opposited
balance_format+='/ ? -1 : 1)), 20, 20 + int(prepend_width), true, color), bold if should_bold)) %(!options.flat ? depth_spacer : "") %-(ansify_if(ansify_if(partial_account(options.flat), blue if color), bold if should_bold)) \n%/%$1\n%/%(prepend_width ? " " * int(prepend_width) : "")--------------------\n'
#echo "$balance_format"


ledger \
    balance \
    --file main.ledger \
    --no-pager \
    --no-total \
    --date-format %Y-%m-%d \
    --sort date \
    --pedantic \
    --check-payees \
    --exchange EUR \
    --balance-format "$balance_format" \
    $*



